default: &default
  adapter: postgresql
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: corp
  password: corp
  template: template0

development:
  <<: *default
  database: corp_development

test:
  <<: *default
  database: corp_test

staging:
  <<: *default
  database: corp_staging
  username: corp
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: corp
  password: <%= ENV['CORP_DATABASE_PASSWORD'] %>
